# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/VMD_Pov_Ray_Blur_UI.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VMD_Pov_Ray_Blur_UI(object):
    def setupUi(self, VMD_Pov_Ray_Blur_UI):
        VMD_Pov_Ray_Blur_UI.setObjectName("VMD_Pov_Ray_Blur_UI")
        VMD_Pov_Ray_Blur_UI.resize(764, 679)
        VMD_Pov_Ray_Blur_UI.setMaximumSize(QtCore.QSize(781, 5530))
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(VMD_Pov_Ray_Blur_UI)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_45 = QtWidgets.QLabel(VMD_Pov_Ray_Blur_UI)
        self.label_45.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.gridLayout.addWidget(self.label_45, 6, 3, 1, 2)
        self.warning_label = QtWidgets.QLabel(VMD_Pov_Ray_Blur_UI)
        self.warning_label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.warning_label.setFont(font)
        self.warning_label.setAlignment(QtCore.Qt.AlignCenter)
        self.warning_label.setObjectName("warning_label")
        self.gridLayout.addWidget(self.warning_label, 12, 0, 1, 3)
        self.label_13 = QtWidgets.QLabel(VMD_Pov_Ray_Blur_UI)
        self.label_13.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 3, 1, 2)
        self.label_10 = QtWidgets.QLabel(VMD_Pov_Ray_Blur_UI)
        self.label_10.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 10, 3, 1, 2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.ortho_doubleSpinBox = QtWidgets.QDoubleSpinBox(VMD_Pov_Ray_Blur_UI)
        self.ortho_doubleSpinBox.setMinimumSize(QtCore.QSize(0, 30))
        self.ortho_doubleSpinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.ortho_doubleSpinBox.setFont(font)
        self.ortho_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ortho_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ortho_doubleSpinBox.setDecimals(1)
        self.ortho_doubleSpinBox.setMaximum(9.999999999999e+16)
        self.ortho_doubleSpinBox.setSingleStep(1.0)
        self.ortho_doubleSpinBox.setProperty("value", 100.0)
        self.ortho_doubleSpinBox.setObjectName("ortho_doubleSpinBox")
        self.horizontalLayout_7.addWidget(self.ortho_doubleSpinBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_7, 9, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(VMD_Pov_Ray_Blur_UI)
        self.label_7.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 9, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(VMD_Pov_Ray_Blur_UI)
        self.label_11.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(VMD_Pov_Ray_Blur_UI)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 8, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(VMD_Pov_Ray_Blur_UI)
        self.label_9.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 10, 0, 1, 1)
        self.label = QtWidgets.QLabel(VMD_Pov_Ray_Blur_UI)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 7, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.res_width_spinBox = QtWidgets.QSpinBox(VMD_Pov_Ray_Blur_UI)
        self.res_width_spinBox.setMinimumSize(QtCore.QSize(0, 30))
        self.res_width_spinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.res_width_spinBox.setFont(font)
        self.res_width_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.res_width_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.res_width_spinBox.setMaximum(999999999)
        self.res_width_spinBox.setSingleStep(100)
        self.res_width_spinBox.setProperty("value", 5000)
        self.res_width_spinBox.setObjectName("res_width_spinBox")
        self.horizontalLayout.addWidget(self.res_width_spinBox)
        self.label_12 = QtWidgets.QLabel(VMD_Pov_Ray_Blur_UI)
        self.label_12.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.res_height_spinBox = QtWidgets.QSpinBox(VMD_Pov_Ray_Blur_UI)
        self.res_height_spinBox.setMinimumSize(QtCore.QSize(0, 30))
        self.res_height_spinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.res_height_spinBox.setFont(font)
        self.res_height_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.res_height_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.res_height_spinBox.setMaximum(999999999)
        self.res_height_spinBox.setSingleStep(100)
        self.res_height_spinBox.setProperty("value", 5000)
        self.res_height_spinBox.setObjectName("res_height_spinBox")
        self.horizontalLayout.addWidget(self.res_height_spinBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.depth_doubleSpinBox = QtWidgets.QDoubleSpinBox(VMD_Pov_Ray_Blur_UI)
        self.depth_doubleSpinBox.setMinimumSize(QtCore.QSize(0, 30))
        self.depth_doubleSpinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.depth_doubleSpinBox.setFont(font)
        self.depth_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.depth_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.depth_doubleSpinBox.setDecimals(1)
        self.depth_doubleSpinBox.setMaximum(9.999999999999e+16)
        self.depth_doubleSpinBox.setSingleStep(1.0)
        self.depth_doubleSpinBox.setProperty("value", 50.0)
        self.depth_doubleSpinBox.setObjectName("depth_doubleSpinBox")
        self.horizontalLayout_5.addWidget(self.depth_doubleSpinBox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_5, 7, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(VMD_Pov_Ray_Blur_UI)
        self.label_41.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.gridLayout.addWidget(self.label_41, 5, 3, 1, 2)
        self.line_8 = QtWidgets.QFrame(VMD_Pov_Ray_Blur_UI)
        self.line_8.setMinimumSize(QtCore.QSize(0, 5))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 2, 0, 1, 5)
        self.label_43 = QtWidgets.QLabel(VMD_Pov_Ray_Blur_UI)
        self.label_43.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout.addWidget(self.label_43, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.focal_atom_radioButton = QtWidgets.QRadioButton(VMD_Pov_Ray_Blur_UI)
        self.focal_atom_radioButton.setText("")
        self.focal_atom_radioButton.setObjectName("focal_atom_radioButton")
        self.horizontalLayout_4.addWidget(self.focal_atom_radioButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.focal_atom_lineEdit = QtWidgets.QLineEdit(VMD_Pov_Ray_Blur_UI)
        self.focal_atom_lineEdit.setMinimumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.focal_atom_lineEdit.setFont(font)
        self.focal_atom_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.focal_atom_lineEdit.setObjectName("focal_atom_lineEdit")
        self.horizontalLayout_4.addWidget(self.focal_atom_lineEdit)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(VMD_Pov_Ray_Blur_UI)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 11, 0, 1, 5)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.manual_focal_radioButton = QtWidgets.QRadioButton(VMD_Pov_Ray_Blur_UI)
        self.manual_focal_radioButton.setText("")
        self.manual_focal_radioButton.setObjectName("manual_focal_radioButton")
        self.horizontalLayout_26.addWidget(self.manual_focal_radioButton)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem9)
        self.manual_focal_doubleSpinBox = QtWidgets.QDoubleSpinBox(VMD_Pov_Ray_Blur_UI)
        self.manual_focal_doubleSpinBox.setMinimumSize(QtCore.QSize(0, 30))
        self.manual_focal_doubleSpinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.manual_focal_doubleSpinBox.setFont(font)
        self.manual_focal_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.manual_focal_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.manual_focal_doubleSpinBox.setDecimals(2)
        self.manual_focal_doubleSpinBox.setMaximum(9.999999999999e+16)
        self.manual_focal_doubleSpinBox.setSingleStep(0.05)
        self.manual_focal_doubleSpinBox.setProperty("value", 1.0)
        self.manual_focal_doubleSpinBox.setObjectName("manual_focal_doubleSpinBox")
        self.horizontalLayout_26.addWidget(self.manual_focal_doubleSpinBox)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem11)
        self.gridLayout.addLayout(self.horizontalLayout_26, 5, 1, 1, 1)
        self.line = QtWidgets.QFrame(VMD_Pov_Ray_Blur_UI)
        self.line.setMinimumSize(QtCore.QSize(20, 0))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 2, 8, 1)
        self.gen_pov_filename_pushButton = QtWidgets.QPushButton(VMD_Pov_Ray_Blur_UI)
        self.gen_pov_filename_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gen_pov_filename_pushButton.setFont(font)
        self.gen_pov_filename_pushButton.setStyleSheet("color: rgb(0, 0, 255);")
        self.gen_pov_filename_pushButton.setObjectName("gen_pov_filename_pushButton")
        self.gridLayout.addWidget(self.gen_pov_filename_pushButton, 1, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(VMD_Pov_Ray_Blur_UI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setMinimumSize(QtCore.QSize(0, 85))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.gridLayout.addWidget(self.label_40, 0, 0, 1, 5)
        self.label_42 = QtWidgets.QLabel(VMD_Pov_Ray_Blur_UI)
        self.label_42.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout.addWidget(self.label_42, 5, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(VMD_Pov_Ray_Blur_UI)
        self.label_44.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout.addWidget(self.label_44, 6, 0, 1, 1)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem12)
        self.CPK_to_remove_lineEdit = QtWidgets.QLineEdit(VMD_Pov_Ray_Blur_UI)
        self.CPK_to_remove_lineEdit.setMinimumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.CPK_to_remove_lineEdit.setFont(font)
        self.CPK_to_remove_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.CPK_to_remove_lineEdit.setObjectName("CPK_to_remove_lineEdit")
        self.horizontalLayout_25.addWidget(self.CPK_to_remove_lineEdit)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem13)
        self.gridLayout.addLayout(self.horizontalLayout_25, 6, 1, 1, 1)
        self.pov_filename_lineEdit = QtWidgets.QLineEdit(VMD_Pov_Ray_Blur_UI)
        self.pov_filename_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.pov_filename_lineEdit.setFont(font)
        self.pov_filename_lineEdit.setObjectName("pov_filename_lineEdit")
        self.gridLayout.addWidget(self.pov_filename_lineEdit, 1, 1, 1, 3)
        self.load_pov_file_pushButton = QtWidgets.QPushButton(VMD_Pov_Ray_Blur_UI)
        self.load_pov_file_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.load_pov_file_pushButton.setFont(font)
        self.load_pov_file_pushButton.setStyleSheet("color: rgb(0, 0, 255);")
        self.load_pov_file_pushButton.setObjectName("load_pov_file_pushButton")
        self.gridLayout.addWidget(self.load_pov_file_pushButton, 1, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(VMD_Pov_Ray_Blur_UI)
        self.label_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 7, 3, 1, 2)
        self.submit_pushButton = QtWidgets.QPushButton(VMD_Pov_Ray_Blur_UI)
        self.submit_pushButton.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.submit_pushButton.setFont(font)
        self.submit_pushButton.setStyleSheet("")
        self.submit_pushButton.setObjectName("submit_pushButton")
        self.gridLayout.addWidget(self.submit_pushButton, 12, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(VMD_Pov_Ray_Blur_UI)
        self.label_6.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 3, 1, 2)
        self.label_8 = QtWidgets.QLabel(VMD_Pov_Ray_Blur_UI)
        self.label_8.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 9, 3, 1, 2)
        self.label_4 = QtWidgets.QLabel(VMD_Pov_Ray_Blur_UI)
        self.label_4.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 8, 3, 1, 2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem14)
        self.field_width_doubleSpinBox = QtWidgets.QDoubleSpinBox(VMD_Pov_Ray_Blur_UI)
        self.field_width_doubleSpinBox.setMinimumSize(QtCore.QSize(0, 30))
        self.field_width_doubleSpinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.field_width_doubleSpinBox.setFont(font)
        self.field_width_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.field_width_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.field_width_doubleSpinBox.setDecimals(1)
        self.field_width_doubleSpinBox.setMaximum(9.999999999999e+16)
        self.field_width_doubleSpinBox.setSingleStep(1.0)
        self.field_width_doubleSpinBox.setProperty("value", 50.0)
        self.field_width_doubleSpinBox.setObjectName("field_width_doubleSpinBox")
        self.horizontalLayout_8.addWidget(self.field_width_doubleSpinBox)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem15)
        self.gridLayout.addLayout(self.horizontalLayout_8, 10, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem16)
        self.blur_sampling_spinBox = QtWidgets.QSpinBox(VMD_Pov_Ray_Blur_UI)
        self.blur_sampling_spinBox.setMinimumSize(QtCore.QSize(0, 30))
        self.blur_sampling_spinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.blur_sampling_spinBox.setFont(font)
        self.blur_sampling_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.blur_sampling_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.blur_sampling_spinBox.setMinimum(1)
        self.blur_sampling_spinBox.setMaximum(999999999)
        self.blur_sampling_spinBox.setProperty("value", 80)
        self.blur_sampling_spinBox.setObjectName("blur_sampling_spinBox")
        self.horizontalLayout_6.addWidget(self.blur_sampling_spinBox)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem17)
        self.gridLayout.addLayout(self.horizontalLayout_6, 8, 1, 1, 1)
        self.draft_submit_pushButton = QtWidgets.QPushButton(VMD_Pov_Ray_Blur_UI)
        self.draft_submit_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.draft_submit_pushButton.setFont(font)
        self.draft_submit_pushButton.setStyleSheet("")
        self.draft_submit_pushButton.setObjectName("draft_submit_pushButton")
        self.gridLayout.addWidget(self.draft_submit_pushButton, 12, 3, 1, 1)
        self.horizontalLayout_27.addLayout(self.gridLayout)

        self.retranslateUi(VMD_Pov_Ray_Blur_UI)
        QtCore.QMetaObject.connectSlotsByName(VMD_Pov_Ray_Blur_UI)

    def retranslateUi(self, VMD_Pov_Ray_Blur_UI):
        _translate = QtCore.QCoreApplication.translate
        VMD_Pov_Ray_Blur_UI.setWindowTitle(_translate("VMD_Pov_Ray_Blur_UI", "VMD Pov-Ray Blur Editor by LYH"))
        self.label_45.setText(_translate("VMD_Pov_Ray_Blur_UI", "Remove selected CPK representation(s)\n"
"(mol-ID:repr-ID mol-ID-2:repr-ID-2) \n"
"e.g. \"0:1 2:5\" to delete Mol0-Repr1 & Mol2-Repr5"))
        self.warning_label.setText(_translate("VMD_Pov_Ray_Blur_UI", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ff0000;\">Warning! Only .pov file from VMD 1.9.3 is supported.</span></p></body></html>"))
        self.label_13.setText(_translate("VMD_Pov_Ray_Blur_UI", "Width * Height, ratio locked"))
        self.label_10.setText(_translate("VMD_Pov_Ray_Blur_UI", "Larger = Zoom out\n"
"Recom. 50"))
        self.label_7.setText(_translate("VMD_Pov_Ray_Blur_UI", "Orthographicality: "))
        self.label_11.setText(_translate("VMD_Pov_Ray_Blur_UI", "Resolution: "))
        self.label_3.setText(_translate("VMD_Pov_Ray_Blur_UI", "Blur Sampling: "))
        self.label_9.setText(_translate("VMD_Pov_Ray_Blur_UI", "Field width: "))
        self.label.setText(_translate("VMD_Pov_Ray_Blur_UI", "Depth of view: "))
        self.label_12.setText(_translate("VMD_Pov_Ray_Blur_UI", "*"))
        self.label_41.setText(_translate("VMD_Pov_Ray_Blur_UI", "Manually set the focal point by a depth.\n"
"e.g. \"1.35\", trial-and-errors are needed"))
        self.label_43.setText(_translate("VMD_Pov_Ray_Blur_UI", "Focal Atom(s): "))
        self.gen_pov_filename_pushButton.setText(_translate("VMD_Pov_Ray_Blur_UI", "Gen .pov Filename"))
        self.label_40.setText(_translate("VMD_Pov_Ray_Blur_UI", "<html><head/><body><p>Set whatever you like in VMD, <span style=\" font-weight:600; color:#ff0000;\">[File]</span>-<span style=\" font-weight:600; color:#ff0000;\">[Render]</span><span style=\" color:#000000;\">, using </span><span style=\" font-weight:600; color:#ff0000;\">[POV-Ray 3.6]</span></p><p><span style=\" font-weight:600; color:#0000ff;\">[Gen .pov filename]</span> then <span style=\" font-weight:600;\">Ctrl+V</span> to VMD <span style=\" font-weight:600; color:#ff0000;\">[File Render Controls]</span> - <span style=\" font-weight:600; color:#ff0000;\">[Filenames:]</span>. Delete everything in <span style=\" font-weight:600; color:#ff0000;\">[Render Command:]</span></p><p>Click <span style=\" font-weight:600; color:#ff0000;\">[Start Rendering]</span> in VMD; Then click <span style=\" font-weight:600; color:#0000ff;\">[Load VMD generated .pov file]</span> here</p></body></html>"))
        self.label_42.setText(_translate("VMD_Pov_Ray_Blur_UI", "Manual Focal Distance: "))
        self.label_44.setText(_translate("VMD_Pov_Ray_Blur_UI", "Remove CPK Molecules:"))
        self.load_pov_file_pushButton.setText(_translate("VMD_Pov_Ray_Blur_UI", "Load VMD generated .pov file"))
        self.label_2.setText(_translate("VMD_Pov_Ray_Blur_UI", "Smaller = Stronger blur (shallower depth of field)\n"
"+Infinity = No blur; (0,infinity)"))
        self.submit_pushButton.setText(_translate("VMD_Pov_Ray_Blur_UI", "Submit to Pov-Ray Rendering"))
        self.label_6.setText(_translate("VMD_Pov_Ray_Blur_UI", "Focal point atom index(es) (on their geometry center). \n"
"e.g. \"0\" or \"0 2 13\" for single molecule ([mol-ID] = [Repr-ID] = 0);\n"
"      \"0:7\" for multiple molecule ([mol-ID]:[index]) ([Repr-ID] = 0);\n"
"      \"0:1:7\" to select representation ([mol-ID]:[repr-ID]:[index]). \n"
"Use \"P\" mode in VMD to check the mol. ID and atom index)"))
        self.label_8.setText(_translate("VMD_Pov_Ray_Blur_UI", "Smaller = More perceptible perspective\n"
">100 for \"pure\" orthographic; (0, +infinity), recom. [1,200]"))
        self.label_4.setText(_translate("VMD_Pov_Ray_Blur_UI", "Larger = Higher blur quality & longer rendering time\n"
">85 for indiscernible noise; [0,infinity)"))
        self.draft_submit_pushButton.setText(_translate("VMD_Pov_Ray_Blur_UI", "Generate Draft Image"))

